<?php
use ValCommon\Tools\Setting;

$sTitle  = "ValVersion ZF2 Version Module ".Setting::get('valversion_version');
$sBorder = str_pad("", strlen($sTitle), '=');
?>
<pre>==<?php echo $sBorder; ?>==
= <?php echo $sTitle; ?> =
==<?php echo $sBorder; ?>==

<?php echo $content; ?>

Current Version: <?php echo $oManager->getCurrent()."\n"; ?>
Latest Version:  <?php echo $oManager->getLatest()."\n"; ?>

Actions:
- <a href='<?php echo $this->url('default', Array('controller' => "version", 'action' => "index"))."?key={$sKey}"; ?>'>Current Status</a>
- <a href='<?php echo $this->url('default', Array('controller' => "version", 'action' => "history"))."?key={$sKey}"; ?>'>Upgrade History</a>
<?php if ($oManager->canUpgrade()): ?>
- <a href='<?php echo $this->url('default', Array('controller' => "version", 'action' => "upgrade"))."?key={$sKey}"; ?>'>Upgrade to Latest</a>
<?php endif; ?>
</pre>
